services:
  mistralai-Mistral-7B-Instruct-v0.3:
    command:
    - --model
    - mistralai/Mistral-7B-Instruct-v0.3
    - --disable-log-requests
    - --trust-remote-code
    - --gpu-memory-utilization
    - '0.32'
    container_name: mistralai-Mistral-7B-Instruct-v0.3
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
              - gpu
              device_ids:
              - '0'
              driver: nvidia
    environment:
    - HUGGING_FACE_HUB_TOKEN=${HF_TOKEN}
    image: vllm/vllm-openai:latest
    ports:
    - 8100:8000
    restart: always
    volumes:
    - ${HUGGINGFACECACHE}:/root/.cache/huggingface
